In [2]:
# NumPy ndarray Object
# 0D array
import numpy as np
arr0=np.array(10)
print(arr0)

10


In [10]:
# 1d array
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [11]:
# id array-index
import numpy as np
arr1=np.array([1,2,3,4,5])
print(arr1)
print(arr1[2])

[1 2 3 4 5]
3


In [13]:
# 2d array
import numpy as np
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)


[[1 2 3]
 [4 5 6]]


In [19]:
## Accessing array elements in 2D
import numpy as np
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2[0,0])
print(arr2[0,1])
print(arr2[0,2])
print(arr2[1,0])
print(arr2[1,1])
print(arr2[1,2])

1
2
3
4
5
6


In [20]:
# 3d array
import numpy as np
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [28]:
## Accessing array elements in 3D
import numpy as np
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3[0,0,0])
print(arr3[0,0,1])
print(arr3[0,0,2])
print(arr3[0,1,0])
print(arr3[0,1,1])
print(arr3[1,0,0])
print(arr3[1,0,1])
print(arr3[1,0,2])
print(arr3[1,1,0])
print(arr3[1,1,1])
print(arr3[1,1,2])

1
2
3
4
5
7
8
9
10
11
12


In [35]:
# add
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(arr[1]+arr[2])

[1 2 3 4]
5


In [33]:
# even nos
import numpy as np
arr = np.array([0, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

(array([0, 1, 3, 5, 7], dtype=int64),)


In [36]:
# Find the indexes where the value is 4
# using where in arrays returns the location
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [37]:
# Sort the array:
import numpy as np
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [58]:
#soring in reverse order
import numpy as np
arr = np.array([3, 2, 0, 1])
desc=np.sort(arr)[::-1]
print(desc)

[3 2 1 0]


In [40]:
## Arithmetic Functions
# add,subract,multiply
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
result_a=np.add(arr1,arr2)
result_s=np.subtract(arr1,arr2)
result_m=np.multiply(arr1,arr2)
result_sq=np.sqrt(arr1)
print(result_a)
print(result_s)
print(result_m)
print(result_sq)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[1.         1.41421356 1.73205081]


In [2]:
import numpy as np

arr1=np.array([4,4,4])
result=np.sqrt(arr1)4
print(result)

[2. 2. 2.]


In [41]:
# shape
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [42]:
# size
import numpy as np
arr=np.array([4,5,6])
print(arr.size)

3


In [51]:
#reshape
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr.reshape(1,6))
print(arr.reshape(2,3))
print(arr.reshape(3,2))

[[1 2 3 4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [57]:
import numpy as np
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3)
print("\n")
print(arr3[1])
print("\n")
print(arr3[1,1])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


[[ 7  8  9]
 [10 11 12]]


[10 11 12]


In [61]:
import numpy as np
arr1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr2=np.array([[[2,3,4],[5,6,7]],[[8,9,10],[11,12,13]]])
result_a=np.add(arr1,arr2)
result_s=np.subtract(arr1,arr2)
result_m=np.multiply(arr1,arr2)
result_sq=np.sqrt(arr1)
print(result_a)
print("\n")
print(result_s)
print("\n")
print(result_m)
print("\n")
print(result_sq)

              

[[[ 3  5  7]
  [ 9 11 13]]

 [[15 17 19]
  [21 23 25]]]


[[[-1 -1 -1]
  [-1 -1 -1]]

 [[-1 -1 -1]
  [-1 -1 -1]]]


[[[  2   6  12]
  [ 20  30  42]]

 [[ 56  72  90]
  [110 132 156]]]


[[[1.         1.41421356 1.73205081]
  [2.         2.23606798 2.44948974]]

 [[2.64575131 2.82842712 3.        ]
  [3.16227766 3.31662479 3.46410162]]]


In [1]:
import numpy as np
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3
